spring.application.name=chat
spring.datasource.url=jdbc:mysql://localhost:3306/finance
spring.datasource.username=root
spring.datasource.password=Pass@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

spring.ai.model.chat=openai
spring.ai.openai.api-key=sk_zgl5ooip_fkT3wEJUQ2fGOC5I0HusZvM3
spring.ai.openai.base-url=https://api.sarvam.ai/v1/chat/completions
spring.ai.openai.chat.options.model=sarvam-105b

SARVAM_API_KEY=sk_zgl5ooip_fkT3wEJUQ2fGOC5I0HusZvM3